export enum ChatActionType {
    CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE',
    MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
    UPDATE_CHAT = 'UPDATE_CHAT',
    GET_USERS = 'GET_USERS',
    UPDATE_USERS = 'UPDATE_USERS',
}
